flowchart LR

SE[Software Engineer]
--> SSE[Senior Software Engineer]
--> TL[Technical Lead]
--> SA[Solution Architect]
--> CA[Cloud Architect]
--> EA[Enterprise Architect]
--> CTO[Technology Executive]

style SA fill:#CCE5FF
style CA fill:#D5F5E3
style EA fill:#FDEBD0
style CTO fill:#FADBD8