flowchart LR

Developer --> Senior_Engineer

Senior_Engineer --> Technical_Lead

Technical_Lead --> Solution_Architect

Solution_Architect --> Enterprise_Architect

Enterprise_Architect --> CTO

style Solution_Architect fill:#CCE5FF